export const FINANCE_RECEIVABLES_SNAPSHOT_SOURCE = 'BSALE_UNPAID_DOCUMENTS_SNAPSHOT' as const
export const FINANCE_RECEIVABLES_HISTORICAL_SOURCE = 'BSALE_DOCUMENTS_PAYMENTS_HISTORICAL' as const

export type FinanceReceivablesSource =
  | typeof FINANCE_RECEIVABLES_SNAPSHOT_SOURCE
  | typeof FINANCE_RECEIVABLES_HISTORICAL_SOURCE
