'use client'
import { useState } from 'react'
import { upsertCommissionSellerProfile, type CommissionSeller, type CommissionSellerType } from '@/app/actions/comercial/commissions'

export function CommissionSellersConfig({ sellers, onSaved, setError }: { sellers: CommissionSeller[]; onSaved: () => Promise<void>; setError: (message: string) => void }) {
  const [saving, setSaving] = useState<number | null>(null)
  const save = async (seller: CommissionSeller, form: HTMLFormElement) => { const data = new FormData(form); setSaving(seller.seller_bsale_id); try { await upsertCommissionSellerProfile({ seller_bsale_id: seller.seller_bsale_id, seller_name: seller.seller_name || '', seller_type: data.get('type') as CommissionSellerType, active: data.get('active') === 'on', is_commissionable: data.get('commissionable') === 'on', notes: String(data.get('notes') || '') }); await onSaved() } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar') } finally { setSaving(null) } }
  return <div><h3>Vendedores</h3><table><thead><tr><th>Vendedor</th><th>Tipo</th><th>Comisionable</th><th>Activo</th><th>Notas</th><th /></tr></thead><tbody>{sellers.map(s => <tr key={s.seller_bsale_id}><td>{s.seller_name}<small>{s.seller_profile_id ? s.is_commissionable ? 'Comisionable' : 'No comisionable' : 'Sin perfil'}</small></td><td colSpan={5}><form onSubmit={e => { e.preventDefault(); void save(s, e.currentTarget) }}><select name="type" defaultValue={s.seller_type}>{(['FIELD','ADMIN','MANAGEMENT','DISPATCH','OTHER'] as CommissionSellerType[]).map(v => <option key={v}>{v}</option>)}</select><label><input name="commissionable" type="checkbox" defaultChecked={s.is_commissionable}/>Comisionable</label><label><input name="active" type="checkbox" defaultChecked={s.profile_active ?? true}/>Activo</label><input name="notes" defaultValue={s.notes || ''} placeholder="Notas"/><button disabled={saving===s.seller_bsale_id}>Guardar</button></form></td></tr>)}</tbody></table></div>
}
