import type { CSSProperties } from 'react'

export const financialThemeStyle = {
  '--theme-bg': '#EFE9E1',
  '--theme-bg-gradient-start': '#EFE9E1',
  '--theme-bg-gradient-mid': '#EFE9E1',
  '--theme-bg-gradient-end': '#EFE9E1',
  '--theme-surface': '#EFE9E1',
  '--theme-surface-hover': '#D1C7BD',
  '--theme-accent': '#72383D',
  '--theme-accent-hover': '#5D2E32',
  '--theme-accent-muted': 'rgba(114, 56, 61, 0.12)',
  '--theme-text': '#322D29',
  '--theme-text-muted': '#6D625B',
  '--theme-text-accent': '#72383D',
  '--theme-border': '#D1C7BD',
  '--theme-border-accent': 'rgba(114, 56, 61, 0.35)',
  '--theme-glow': 'rgba(114, 56, 61, 0.08)',
  '--theme-glow-intense': 'rgba(114, 56, 61, 0.18)',
  '--theme-base': '#EFE9E1',
  '--theme-panel': '#EFE9E1',
  '--theme-panel-hover': '#D1C7BD',
  '--theme-primary': '#72383D',
  '--theme-secondary': '#AC9C8D',
  '--theme-sidebar-bg': '#322D29',
  '--theme-sidebar-surface': '#322D29',
  '--theme-sidebar-border': '#AC9C8D',
  '--theme-sidebar-text': '#EFE9E1',
  '--theme-sidebar-muted': '#D1C7BD',
  '--theme-sidebar-hover': '#5D2E32',
  '--theme-sidebar-active': '#72383D',
  '--theme-sidebar-active-text': '#EFE9E1',
  '--theme-sidebar-accent': '#AC9C8D',
} as CSSProperties
